import { EventInfo } from "@/types";

export const events: Record<string, EventInfo> = {
  haldi: {
    slug: "haldi",
    title: "Haldi Ceremony",
    subtitle: "పసుపు కుంకుమ",
    tagline: "A celebration of turmeric blessings & joy",
    date: "2026-04-19",
    time: "10:00 AM - 1:00 PM",
    venue: "Konkimalla Family Residence",
    venueAddress: "3670 Matt Hwy, Cumming, GA 30028",
    googleMapsUrl: "https://maps.google.com/?q=3670+Matt+Hwy+Cumming+GA+30028",
    dressCode: "Yellow / Traditional Indian Attire",
    description:
      "Join us for the auspicious Haldi ceremony where turmeric paste is lovingly applied to the bride and groom, symbolizing purification and blessings for their new journey together.",
    theme: {
      primary: "#F59E0B",
      secondary: "#FCD34D",
      accent: "#92400E",
      bg: "#FFFBEB",
      cardBg: "#FFFFFF",
      text: "#78350F",
      gradient: "from-yellow-300 via-amber-400 to-yellow-500",
    },
    heroImage: "/images/shared/DSC05984.jpg",
    galleryImages: [
      "/images/shared/DSC05872.jpg",
      "/images/shared/DSC06256.jpg",
      "/images/shared/DSC05897.jpg",
    ],
    decorativeEmoji: "🌼",
  },
  "karthik-upanayanam": {
    slug: "karthik-upanayanam",
    title: "Karthik's Upanayanam",
    subtitle: "ఉపనయనం",
    tagline: "Sacred thread ceremony",
    date: "2026-04-20",
    time: "8:00 AM - 12:00 PM",
    venue: "Konkimalla Family Residence",
    venueAddress: "435 Fairview Cir, Roswell, GA 30076",
    googleMapsUrl: "https://maps.google.com/?q=435+Fairview+Cir+Roswell+GA+30076",
    dressCode: "Traditional White / Beige",
    description:
      "The sacred Upanayanam ceremony marks a spiritual milestone — the initiation into Vedic learning and the beginning of a disciplined, purposeful life.",
    theme: {
      primary: "#D97706",
      secondary: "#FDE68A",
      accent: "#92400E",
      bg: "#FFF8F0",
      cardBg: "#FFFFFF",
      text: "#78350F",
      gradient: "from-amber-200 via-orange-300 to-amber-400",
    },
    heroImage: "/images/shared/DSC06256.jpg",
    galleryImages: [
      "/images/shared/DSC05897.jpg",
      "/images/shared/DSC05386.jpg",
      "/images/shared/DSC05476-2-Edit.jpg",
    ],
    decorativeEmoji: "🙏",
  },
  mehendi: {
    slug: "mehendi",
    title: "Mehendi",
    subtitle: "మెహెందీ",
    tagline: "An evening of henna art & celebration",
    date: "2026-04-20",
    time: "5:00 PM - 10:00 PM",
    venue: "Konkimalla Family Residence",
    venueAddress: "435 Fairview Cir, Roswell, GA 30076",
    googleMapsUrl: "https://maps.google.com/?q=435+Fairview+Cir+Roswell+GA+30076",
    dressCode: "Green / Traditional Indian Attire",
    description:
      "An enchanting evening of intricate henna designs, music, and celebration as the bride is adorned with beautiful mehendi patterns symbolizing love and prosperity.",
    theme: {
      primary: "#059669",
      secondary: "#6EE7B7",
      accent: "#064E3B",
      bg: "#ECFDF5",
      cardBg: "#FFFFFF",
      text: "#064E3B",
      gradient: "from-emerald-300 via-green-400 to-emerald-500",
    },
    heroImage: "/images/shared/DSC05476-2-Edit.jpg",
    galleryImages: [
      "/images/shared/DSC05926-2.jpg",
      "/images/shared/Neelu-Aditya_AR50419.jpg",
      "/images/shared/DSC05872.jpg",
    ],
    decorativeEmoji: "🌿",
  },
  sangeeth: {
    slug: "sangeeth",
    title: "Sangeeth Night",
    subtitle: "సంగీతం",
    tagline: "A night of music, dance & celebration",
    date: "2026-04-21",
    time: "6:00 PM - 11:00 PM",
    venue: "Venue Hall",
    venueAddress: "3170 Peachtree Parkway, Suwanee, GA 30024",
    googleMapsUrl:
      "https://maps.google.com/?q=3170+Peachtree+Parkway+Suwanee+GA+30024",
    dressCode: "Glamorous / Indo-Western",
    description:
      "Get ready for an unforgettable evening of music, dance performances, and celebration as families come together to honor the couple with song and joy.",
    theme: {
      primary: "#94A3B8",
      secondary: "#CBD5E1",
      accent: "#D4AF37",
      bg: "#0C0C10",
      cardBg: "#1a1a2e",
      text: "#E2E8F0",
      gradient: "from-slate-400 via-gray-500 to-slate-600",
    },
    heroImage: "/images/shared/DSC05897.jpg",
    galleryImages: [
      "/images/shared/DSC05386.jpg",
      "/images/shared/DSC05223-2.jpg",
      "/images/shared/DSC05984.jpg",
    ],
    decorativeEmoji: "🎶",
  },
  pellikuthuru: {
    slug: "pellikuthuru",
    title: "Pellikuthuru",
    subtitle: "పెళ్ళికూతురు",
    tagline: "Celebrating the bride's journey",
    date: "2026-04-22",
    time: "9:00 AM - 12:00 PM",
    venue: "Bride's Family Residence",
    venueAddress: "435 Fairview Cir, Roswell, GA 30076",
    googleMapsUrl: "https://maps.google.com/?q=435+Fairview+Cir+Roswell+GA+30076",
    dressCode: "Traditional Red & Gold Saree / Lehenga",
    description:
      "A beautiful Telugu tradition celebrating the bride as she prepares for her wedding day, surrounded by love, laughter, and blessings from family and friends.",
    theme: {
      primary: "#DC2626",
      secondary: "#F87171",
      accent: "#D4A017",
      bg: "#FEF2F2",
      cardBg: "#FFFFFF",
      text: "#7F1D1D",
      gradient: "from-red-500 via-rose-600 to-red-700",
    },
    heroImage: "/images/shared/DSC05476-2-Edit.jpg",
    galleryImages: [
      "/images/shared/DSC05926-2.jpg",
      "/images/shared/Neelu-Aditya_AR50419.jpg",
      "/images/shared/DSC05872.jpg",
    ],
    decorativeEmoji: "👰",
  },
  pellikoduku: {
    slug: "pellikoduku",
    title: "Pellikoduku",
    subtitle: "పెళ్ళికొడుకు",
    tagline: "Honoring the groom's celebration",
    date: "2026-04-22",
    time: "9:00 AM - 12:00 PM",
    venue: "Groom's Family Residence",
    venueAddress: "6390 Bennett Rd, Cumming, GA 30041",
    googleMapsUrl: "https://maps.google.com/?q=6390+Bennett+Rd+Cumming+GA+30041",
    dressCode: "Traditional Cream & Gold Kurta / Sherwani",
    description:
      "A joyous Telugu tradition celebrating the groom as he embarks on a new chapter, blessed by family and friends with love and festive spirit.",
    theme: {
      primary: "#D4A017",
      secondary: "#F5E6CC",
      accent: "#8B6914",
      bg: "#FFFDF7",
      cardBg: "#FFFFFF",
      text: "#44340A",
      gradient: "from-amber-300 via-yellow-200 to-amber-400",
    },
    heroImage: "/images/shared/DSC05223-2.jpg",
    galleryImages: [
      "/images/shared/DSC05984.jpg",
      "/images/shared/DSC05872.jpg",
      "/images/shared/DSC06256.jpg",
    ],
    decorativeEmoji: "🤵",
  },
  "aditya-upanayanam": {
    slug: "aditya-upanayanam",
    title: "Aditya's Upanayanam",
    subtitle: "ఉపనయనం",
    tagline: "Sacred thread ceremony",
    date: "2026-04-22",
    time: "7:00 AM - 12:00 PM",
    venue: "Hanuman Mandir",
    venueAddress: "390 Cumming St B, Alpharetta, GA 30004",
    googleMapsUrl:
      "https://maps.google.com/?q=390+Cumming+St+B+Alpharetta+GA+30004",
    dressCode: "Traditional White / Beige",
    description:
      "The sacred Upanayanam ceremony marks a spiritual milestone — the initiation into Vedic learning and the beginning of a disciplined, purposeful life.",
    theme: {
      primary: "#B45309",
      secondary: "#FDE68A",
      accent: "#78350F",
      bg: "#FFF8F0",
      cardBg: "#FFFFFF",
      text: "#78350F",
      gradient: "from-orange-200 via-amber-300 to-orange-400",
    },
    heroImage: "/images/shared/DSC05897.jpg",
    galleryImages: [
      "/images/shared/DSC06256.jpg",
      "/images/shared/DSC05386.jpg",
      "/images/shared/DSC05984.jpg",
    ],
    decorativeEmoji: "🙏",
  },
  pelli: {
    slug: "pelli",
    title: "Pelli — The Wedding",
    subtitle: "పెళ్ళి",
    tagline: "Two souls, one beautiful journey",
    date: "2026-04-23",
    time: "8:00 AM - 2:00 PM",
    venue: "Hindu Temple of Atlanta",
    venueAddress: "5851 GA-85, Riverdale, GA 30274",
    googleMapsUrl: "https://maps.google.com/?q=Hindu+Temple+of+Atlanta",
    dressCode: "Formal Indian / Western Attire",
    description:
      "The main wedding ceremony — a sacred union of two souls, two families, and a lifetime of love. Join us as we celebrate this once-in-a-lifetime moment.",
    theme: {
      primary: "#8B1A1A",
      secondary: "#F5E6CC",
      accent: "#C5A028",
      bg: "#FFF8F0",
      cardBg: "#FFFFFF",
      text: "#3D1A1A",
      gradient: "from-red-900 via-rose-800 to-red-900",
    },
    heroImage: "/images/pelli/DSC05926-2.jpg",
    galleryImages: [
      "/images/pelli/DSC05223-2.jpg",
      "/images/pelli/DSC05386.jpg",
      "/images/pelli/DSC05476-2-Edit.jpg",
      "/images/pelli/DSC05872.jpg",
    ],
    decorativeEmoji: "💍",
    venueImage: "/images/temple.jpg",
  },
  "satyanarayana-swami-vratam-aditya": {
    slug: "satyanarayana-swami-vratam-aditya",
    title: "Satyanarayana Swami Vratam",
    subtitle: "సత్యనారాయణ స్వామి వ్రతం",
    tagline: "A sacred puja for divine blessings — Groom's side",
    date: "2026-04-25",
    time: "9:00 AM - 1:00 PM",
    venue: "Groom's Family Residence",
    venueAddress: "6390 Bennett Rd, Cumming, GA 30041",
    googleMapsUrl: "https://maps.google.com/?q=6390+Bennett+Rd+Cumming+GA+30041",
    dressCode: "Traditional Indian Attire",
    description:
      "A traditional Hindu puja performed to seek the blessings of Lord Satyanarayana for peace, prosperity, and happiness in the couple's married life.",
    theme: {
      primary: "#EA580C",
      secondary: "#FFEDD5",
      accent: "#C2410C",
      bg: "#FFF7ED",
      cardBg: "#FFFFFF",
      text: "#7C2D12",
      gradient: "from-orange-300 via-amber-400 to-orange-500",
    },
    heroImage: "/images/shared/Neelu-Aditya_AR50419.jpg",
    galleryImages: [
      "/images/shared/DSC05984.jpg",
      "/images/shared/DSC06256.jpg",
      "/images/shared/DSC05926-2.jpg",
    ],
    decorativeEmoji: "🙏",
  },
  "satyanarayana-swami-vratam-neelu": {
    slug: "satyanarayana-swami-vratam-neelu",
    title: "Satyanarayana Swami Vratam",
    subtitle: "సత్యనారాయణ స్వామి వ్రతం",
    tagline: "A sacred puja for divine blessings — Bride's side",
    date: "2026-04-26",
    time: "9:00 AM - 1:00 PM",
    venue: "Bride's Family Residence",
    venueAddress: "435 Fairview Cir, Roswell, GA 30076",
    googleMapsUrl: "https://maps.google.com/?q=435+Fairview+Cir+Roswell+GA+30076",
    dressCode: "Traditional Indian Attire",
    description:
      "A traditional Hindu puja performed to seek the blessings of Lord Satyanarayana for peace, prosperity, and happiness in the couple's married life.",
    theme: {
      primary: "#EA580C",
      secondary: "#FFEDD5",
      accent: "#C2410C",
      bg: "#FFF7ED",
      cardBg: "#FFFFFF",
      text: "#7C2D12",
      gradient: "from-orange-300 via-amber-400 to-orange-500",
    },
    heroImage: "/images/shared/DSC05984.jpg",
    galleryImages: [
      "/images/shared/DSC06256.jpg",
      "/images/shared/DSC05926-2.jpg",
      "/images/shared/Neelu-Aditya_AR50419.jpg",
    ],
    decorativeEmoji: "🙏",
  },
};

export const eventOrder = [
  "haldi",
  "karthik-upanayanam",
  "mehendi",
  "sangeeth",
  "pellikuthuru",
  "pellikoduku",
  "aditya-upanayanam",
  "pelli",
  "satyanarayana-swami-vratam-aditya",
  "satyanarayana-swami-vratam-neelu",
];

export function getEvent(slug: string): EventInfo | undefined {
  return events[slug];
}
